DjangoSocialMedia/urls.py
from django.contrib import admin
from django.urls import include, path

from DjangoSocialMedia import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

account/urls.py
from django.urls import path

from account import views

app_name = "account"
urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name="user_register"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
    path(
        "profile/<int:user_id>/",
        views.UserProfileView.as_view(),
        name="user_profile",
    ),
    path(
        "password/reset/",
        views.UserPasswordResetView.as_view(),
        name="user_password_reset",
    ),
    path(
        "password/reset/done/",
        views.UserPasswordResetDoneView.as_view(),
        name="user_password_reset_done",
    ),
    path(
        "password/reset/confirm/<uidb64>/<token>",
        views.UserPasswordResetConfirmView.as_view(),
        name="user_password_reset_confirm",
    ),
    path(
        "password/reset/complete/",
        views.UserPasswordResetCompleteView.as_view(),
        name="user_password_reset_complete",
    ),
    path("follow/<int:user_id>/", views.UserFollowView.as_view(), name="user_follow"),
    path(
        "unfollow/<int:user_id>/",
        views.UserUnFollowView.as_view(),
        name="user_unfollow",
    ),
    path("user/edit/", views.EditUserView.as_view(), name="user_edit")
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
    path(
        "post/<int:post_id>/<slug:post_slug>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path(
        "post/delete/<int:post_id>/",
        views.PostDeleteView.as_view(),
        name="post_delete",
    ),
    path(
        "post/update/<int:post_id>/",
        views.PostUpdateView.as_view(),
        name="post_update",
    ),
    path("post/create/", views.PostCreateView.as_view(), name="post_create"),
    path("post/<int:post_id>/<int:comment_id>/reply/", views.PostAddReplyView.as_view(), name="post_add_reply"),
    path("post/<int:post_id>/like", views.PostLikeView.as_view(), name="post_like")
]

home/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="posts")
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created", "body")

    def __str__(self):
        return f"{self.slug} - {self.updated}"

    def get_absolute_url(self):
        return reverse("home:post_detail", args=(self.pk, self.slug))

    def likes_count(self):
        return self.pvotes.count()

    def user_can_like(self, user: User):
        user_like = user.uvotes.filter(post=self)
        if user_like.exists():
            return False
        return True

class Comment(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="ucomments",
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="pcomments",
    )
    reply = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        related_name="rcomments",
        blank=True,
        null=True,
    )
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"{self.user} - {self.body[:30]}"


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="uvotes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="pvotes")

    def __str__(self):
        return f"{self.user} liked {self.post.slug}"

home/forms.py
from django import forms

from home.models import Comment, Post


class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("body",)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {"body": forms.Textarea(attrs={"class": "form-control"})}


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {"body": forms.Textarea(attrs={"class": "form-control"})}


class PostSearchForm(forms.Form):
    search = forms.CharField()

home/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.utils.text import slugify
from django.views import View

from home.forms import CommentCreateForm, PostCreateUpdateForm, CommentReplyForm, PostSearchForm
from home.models import Post, Comment, Vote


class HomeView(View):
    form_class = PostSearchForm
    template_name = "home/index.html"

    def get(self, request):
        posts = Post.objects.all()
        if request.GET.get("search"):
            posts = posts.filter(body__icontains=request.GET["search"])
        return render(request, self.template_name, {"posts": posts, "form": self.form_class})


class PostDetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm
    template_name = "home/detail.html"
    post_instance = None

    def setup(self, request, *args, **kwargs):
        post_id = kwargs.get("post_id")
        post_slug = kwargs.get("post_slug")
        self.post_instance = get_object_or_404(
            Post,
            pk=post_id,
            slug=post_slug,
        )
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comments = self.post_instance.pcomments.filter(is_reply=False)
        can_like = False

        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like = True
        return render(
            request,
            self.template_name,
            {
                "post": self.post_instance,
                "comments": comments,
                "form": self.form_class,
                "form_reply": self.form_class_reply,
                "can_like": can_like
            },
        )

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = self.post_instance
            new_comment.user = request.user
            new_comment.save()
            messages.success(request, "Your comment submitted successfully.", "success")
            return redirect(
                "home:post_detail",
                self.post_instance.id,
                self.post_instance.slug,
            )


class PostDeleteView(LoginRequiredMixin, View):
    redirect_url = "home:index"

    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        if post.user.pk == request.user.pk:
            post.delete()
            messages.success(request, "Post delete successfully.", "success")
        else:
            messages.error(request, "You can't delete this post.", "danger")

        return redirect(self.redirect_url)


class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm
    post_instance = None

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs.get("post_id"))
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.pk == request.user.pk:
            messages.error(request, "You can't update this post.", "danger")
            return redirect("home:index")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, "home/update.html", {"form": form})

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data["body"][:30])
            new_post.save()
            messages.success(request, "You updated this post", "success")
            return redirect("home:post_detail", post.pk, post.slug)


class PostCreateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, "home/create.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data["body"][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request, "You created new post successfully.", "success")
            return redirect("home:post_detail", new_post.pk, new_post.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post, id=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.is_reply = True
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.save()
            messages.success(request, "Your reply saved successfully", "success")
        return redirect("home:post_detail", post.id, post.slug)


class PostLikeView(LoginRequiredMixin, View):
    redirect_url = "home:post_detail"

    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        like = Vote.objects.filter(post=post, user=request.user)
        if like.exists():
            messages.error(request, "You have already liked this post.", "danger")
        else:
            Vote.objects.create(post=post, user=request.user)
            messages.success(request, "You liked this post.", "success")

        return redirect(self.redirect_url, post.id, post.slug)

home/templates/home/create.html
{% extends 'base.html' %}

{% block title %}
  Create Post
{% endblock %}

{% block content %}
  <form action="{% url 'home:post_create' %}" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
  </form>
{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block title %}
  {{ post.body|truncatewords:2 }}
{% endblock %}

{% block content %}
  {% if request.user.pk == post.user.pk %}
    <a href="{% url 'home:post_delete' post.pk %}" class="btn btn-danger">Delete</a>
    <a href="{% url 'home:post_update' post.pk %}" class="btn btn-info">Update</a>
  {% endif %}

  <p>
    <a href="{% url 'account:user_profile' post.user.pk %}">{{ post.user }}</a> -
    <span>{{ post.updated|date:"Y M j" }}</span>
  </p>
  <p>{{ post.body }}</p>
  <hr>
  {% if request.user.is_authenticated %}
    <a href="{% url 'home:post_like' post.id %}"
       class="{% if not can_like %}disabled{% endif %} btn btn-primary col-md-2">Like {{ post.likes_count }}</a>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Send comment">
    </form><br>
  {% else %}
    <p class="alert alert-danger">Only logged in users can be send comment.</p>
  {% endif %}
  <hr>
  {% for comment in comments %}
    <div class="card bg-dark text-white">
      <p class="card-header">{{ comment.user }} | {{ comment.created|timesince }} ago</p>
      <p class="card-body">{{ comment.body }}</p>
      {% if request.user.is_authenticated %}
        <form action="{% url 'home:post_add_reply' post.id comment.id %}" method="post"
              style="margin-left: 10px; margin-right: 10px">
          {% csrf_token %}
          {{ form_reply.as_p }}
          <input type="submit" value="Send">
        </form>
      {% endif %}
      {% with comment.rcomments.all as replies %}
        {% for reply in replies %}
          <p class="bg-primary p-3 m-2">
            {{ reply.user }} <br> {{ reply.body }}
          </p>
        {% endfor %}
      {% endwith %}
    </div><br>
  {% empty %}
    <p>No comment's yet!</p>
  {% endfor %}


{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}

  <form action="" method="get">
    {{ form.as_p }}
    <input type="submit" value="search">
  </form>
  <br>
  <div class="card">
    {% for post in posts %}
      <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.body|truncatewords:5 }}</a>
    {% endfor %}
  </div>
{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}

{% block title %}
  Post Update
{% endblock %}

{% block content %}
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
  </form>
{% endblock %}